### ISSUE TITLE
Häufigkeit ändert sich nach Änderung nicht, obwohl es erfolgreich sein soll.

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#10]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Ich habe die Häufigkeit auf alle 1 min für 2 Tests laufen lassen, nach der Änderung zu 1 Stunde wurde es anscheinend im Hintergrund nicht angepasst. Nach einem Neustart via systemctl ist immernoch dasselbe, ich vermute das solange Speedtests gemacht werden, bis die nächste volle Stunde erreicht wird (Bug).
<img src="https://imgur.com/a/DuHTSNU">

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Hi! Hast du beim Update auf die neuste Version die Schritte in https://github.com/gnmyt/myspeed/pull/7 beachtet? Schau mal ganz unten bei "timeLevel" nach und füge den Befehl ein. Anders wird das nicht funktionieren

**Comment by pavl21** [comment]
MySpeed wurde komplett neu aufgesetzt, von daher sollte es ja direkt dabei sein.

**Comment by pavl21** [comment]
Zudem ist der Fix fehlerhaft. Es kommt folgender bei mir raus, vielleicht ist es auch nur bei mir.


![image](https://user-images.githubusercontent.com/36771750/174488981-45a8a2a1-2e43-4eb1-a4e1-9ef00f08b0c9.png)

**Comment by gnmyt** [comment]
Hey. Du musst das im Ordner deiner MySpeed-Instanz ausführen. Meistens ist das unter /opt/myspeed

**Comment by gnmyt** [comment]
So, ich nochmal.
Es gab tatsächlich einen Bug, der den Timer falsch gestartet hat, wenn man die Häufigkeit ändert. Der tritt nur beim ändern live auf. Nach einem Restart ist er bei dem gewünschten Wert.
Das ganze wurde jetzt in https://github.com/gnmyt/myspeed/commit/aea7dd7281b882e2bc263344084f98540a01693b behoben und das Problem sollte gelöst sein.
Also einmal updaten bitte 👀
