### ISSUE TITLE
Statusrahmen fehlerhaft nach Neuladen der Seite

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#11]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Wenn MySpeed pausiert wird (in meinem Fall für immer, bis ich es wieder einschalte) und die Seite neu geladen wird, bleibt der Rahmen nicht Orange, sondern ändert sich auf Grün um (so wie als wäre MySpeed aktiv, ist es aber nicht). Nach einem Klick auf die Einstellungen wird, ändert sich die Farbe direkt auf die richtige Farbe (Orange). 

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Hi! Der Bug ist mir aktuell bekannt. Dabei geht es darum, dass der Status von Pausen erst abgefragt wird, wenn Speedtests neu geladen werden. Ich werde das in den nächsten Tagen beheben. :)
