### ISSUE TITLE
Uninstaller-Script

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#12]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Ein Deinstallationsscript von MySpeed. Ist zwar unschön, wenn man es nicht mehr nutzen möchte aber man muss es einem ja nicht schwer machen wenn man es nicht mehr auf dem Linux / Raspberry Pi oder Windows System haben möchte.
Dazu sollte im Script auch folgendes abgefragt werden:
- Soll Nodejs entfernt werden?
- Sollen die Konfigurationen auch entfernt werden? (von MySpeed)

Alles dazugehörige (z.B.: auch Systemctl-Eintrag) sollte dann auch entfernt werden.

**Comment by gnmyt** [comment]
Hey Paul,
das hört sich doch gut an. Ich werde mich mal an das Skript ran setzen :)

**Comment by gnmyt** [comment]
So, der Uninstaller ist fertig (https://github.com/gnmyt/myspeed/commit/a68b16bcc96be7d97246b5757c987e167a1d8ef5). Er wird im neuen Release mit dabei sein 🌚

**Comment by pavl21** [comment]
Es bleiben bei der Deinstallation quasi "Rückstände". Denn nicht jeder nutzt Node.js für andere Zwecke weiter. Diese Software ist für MySpeed notwendig, aber nur wenn es auf dem Linux System läuft.
