### ISSUE TITLE
Test-Häufigkeit selbst als Minutenzahl eingeben

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#15]
### Allgemeines

- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.
- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.

### Deine Idee

Die Häufigkeit selbst optional in Minuten eintragen. z.B.: 5, 10, 15 oder 20 Minuten. Oder auch mal 187 Minuten. 😎

**Comment by gnmyt** [comment]
Ein Button für die manuelle Eingabe kann nicht schaden. Ich füge das ganze die Tage hinzu :)
