### ISSUE TITLE
Primären und sekundären Speedtest-Server

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#19]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

In meinem Fall ist es ab und zu so, das der Speedtest Server selbst nicht erreichbar ist. Somit kommt dann ein Fehler und es fehlen die Werte (natürlich). Meine Idee ist, das man nicht nur einen Speedtest Server, sondern einen primären und einen sekundären angeben kann. Sollte dann der primäre ausfallen und der Test schlug fehl, wird es direkt nochmal mit dem sekundären probiert. Das 2 Server ausfallen ist zwar auch möglich, aber geringer. Wenn der 2. Server zum Testen angewendet wurde und der erste fehlgeschlagen ist, wäre es auch sinnvoll, das nur der erfolgreiche aufgelistet wird.

**Comment by gnmyt** [comment]
Die Idee dahinter verstehe ich. Ein zweiter Speedtest Server kann allerdings zu Verwirrung führen und das Projekt soll einfach gehalten sein. Hätte einen besseren Vorschlag, den ich Umsetzen werde:

Ist ein Speedtest nicht erfolgreich (das ganze nur wenn der Server nicht verfügbar ist), sucht sich die Software selbst nochmal einen Server raus, der online ist. Damit hat man die Garantie, dass der Server immer funktioniert und die Wahrscheinlichkeit, dass der 2. nicht funktioniert liegt bei 0.

**Comment by gnmyt** [comment]
So, in https://github.com/gnmyt/myspeed/commit/d632b3d97c8b53527a58b9d786dc14de18df98db wurde das Feature hinzugefügt. Ich denke mal das passt so :)
