### ISSUE TITLE
MySpeed Weboberfläche nicht erreichbar

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#20]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Bei der Einrichtung wurde sowohl die Stable als auch die Dev Version ausprobiert. Keine der beiden hatte Erfolg.

Bei der Fertigstellung der Installation kam folgendes Ergebnis in der Konsole:
![image](https://user-images.githubusercontent.com/36771750/181995635-e87592de-67bf-4ce0-b0a2-247080d3713e.png)

Beim Versuch die Seite zu erreichen wird man darauf hingewiesen, das die Verbindung verweigert wurde:
![image](https://user-images.githubusercontent.com/36771750/181995653-451152c6-35fe-46b4-803d-9056d9cd264a.png)

Es wird übrigens eine andere IP-Adressenstruktur verwendet als gewöhnlich:
![image](https://user-images.githubusercontent.com/36771750/181995669-dca4d5e5-99cf-44be-b18a-83b363696617.png)

Vielleicht hat es damit zu tun. Die Installation wurde über ein Raspberry Pi 1 durchgeführt.

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Könntest du mal versuchen, MySpeed per Befehl zu starten? Gehe dafür in den Ordner `/opt/myspeed` (`cd /opt/myspeed`) und führe `node server` aus.

**Comment by maaaathis** [comment]
Bei mir tritt der selbe Fehler auf.

Output von `systemctl status myspeed`: 
```
Aug 08 00:38:45 raspberrypi systemd[1]: myspeed.service: Start request repeated too quickly.
Aug 08 00:38:45 raspberrypi systemd[1]: myspeed.service: Failed with result 'start-limit-hit'.
Aug 08 00:38:45 raspberrypi systemd[1]: Failed to start MySpeed.
```

Output von `node server` in `/opt/myspeed`:
`Could not open the database file. Maybe it is damaged?`

**Comment by gnmyt** [comment]
Das Problem ist jetzt tatsächlich schon öfters aufgetreten.
In den meisten Fällen ist das Problem, dass das Modul für die Datenbank in der falschen (bzw. älteren) Node Version kompiliert wurde.
Ein einfaches löschen des `node_modules`-Ordners unter `/opt/myspeed` und dann das neuinstallieren mit `npm install` sollte dabei ausreichen. Hilft das nicht, schau dir mal die Dokumentation unter https://myspeed.gnmyt.dev/troubleshooting an

Damit das zukünftig nicht mehr passiert ändere ich gerade ein paar Sachen ab, die das verursachen. Im nächsten Update sollte das also nicht mehr passieren :)
