### ISSUE TITLE
[Feature] Sammelansicht von mehreren Servern

### ISSUE THREAD

**Issue by Maximilian1021** [gnmyt/MySpeed#221]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Meine Idee wäre, das es ein Webinterface gibt, der von mehreren Servern die Daten abrufen kann, und dann eine übersichtliche Übersicht gibt, welcher Server welche Daten hat...  Mit Graphen und den ganzen Sachen. 

Meine Überlegung war das es eine Hauptseite gibt nennen Wir sie Sammelübersicht.
In dieser werden zum Beispiel von 3 Servern  oder mehr die Ergebnisse der Nerzwerkanalyse angezeigt. 

Also das man nicht auf alle Seiten das Webinterface öffnen muss sondern eine Sammelübersicht hat!

**Comment by gnmyt** [comment]
Moin, vielen Dank für die Einsendung. Die Idee gefällt mir, das würde sich auch perfekt in das neue "Ansicht wechseln"-Feature integrieren (#215). Ich baue das ganze die kommenden Tage ein :)
