### ISSUE TITLE
[Feature] Überprüfung des Pings von Geräten im Heimnetz

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#231]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Es ist immer der Regelfall, das irgendjemand gerade schlechtes Internet Zuhause hat. Das hängt immer mit dem WLAN zusammen. Meine Idee wäre, das man einzelne Geräte im Heimnetz anpingen kann, und somit feststellt ob die gerade eine gute oder schlechte Reichweite haben. Vielleicht kann man das auch als Live-Tester anbieten, um so zu schauen, wo man in seinem Heimnetz den besten Ping hat bzw. wo es schlecht ist. Im Grunde so:
Gerät aus der Heimnetzliste suchen, Ping starten und so positionieren bis der Ping gut ist.

**Comment by gnmyt** [comment]
Hey. Prinzipiell hätte ich nichts gegen ein solches Feature. Ich bin mir nur nicht sicher, ob das wirklich etwas wäre, was in ein Speedtest-Tool passt. MySpeed hat mit der simplen Idee gestartet, einfach das Internet der letzten 24 Stunden anzuzeigen. Mittlerweile speichert es zwar die Daten für einen Monat, die Grundidee von der Software ist allerdings immernoch gleich geblieben: Sie zeigt das Internet an. Das was du beschreibst würde ich eher in ein Netzwerkanalyseprogramm integrieren. 

Ich schreibe mir mal deine Idee auf, denke allerdings nicht, dass es direkt in MySpeed sondern in ein extra Projekt integriert wird.

Trotzdem danke fürs einreichen :)
