### ISSUE TITLE
[Feature] SSL-Verschlüssungshilfe mit Domain als Script anbieten

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#235]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Nicht jeder (auch ich) wüsste nicht, wie man eine Domain mit SSL-Verschlüsselung mit der eigenen MySpeed-Instanz verknüpft. Da wäre ein Tool oder eine Anleitung hilfreich, die dafür gedacht ist.

**Comment by gnmyt** [comment]
Hi! Die Idee ist gut, ich werde den extra Unterpunkt "Guides" in die Dokumentation integrieren und dort den Guide anlegen. Allerdings würde ich das etwas allgemeiner fassen und den Guide zur Installation eines Reverse-Proxies erstellen. Am Ende kommt jedoch sowieso dasselbe raus, da ich die SSL-Anleitung direkt darunter packe.
