### ISSUE TITLE
Bei manueller Einstellung: Server hinzufügen

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#27]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Wenn man manuell einen Server für den Speedtest hinzufügen möchte, benötigt man eine ID. 

Nach dem Speichern der ID wäre es hilfreich, wenn sie getestet wird bevor sie hinterlegt wird. So kann man unangenehme Situationen vermeiden, sollte die ID falsch eingeben worden sein (Sagt man das echt so?).

**Comment by gnmyt** [comment]
Hey. Leider ist mir meines Wissens nach nicht bekannt, dass sich Speedtest-Server validieren lassen.
Da muss vorerst leider erstmal ein simpler Zahlen-Check für hinhalten 😕

Solltest du jedoch einen Weg finden, diese Server zu validieren, lass es mich gerne Wissen und öffne dieses Issue erneut :)
