### ISSUE TITLE
Persistent Default Language & Style + Public View

### ISSUE THREAD

**Issue by jiriteach** [gnmyt/MySpeed#278]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Great work on this. Have tested and works very well.

I have 2 suggestions -

1. Can the default language persist server side? While the language can be set - it’s only for the browser session. Ie. I change it to English - works fine. Open a new browser and it’s in German.
2. While the password protection is great - can there be an option to password protect just the settings? So the stats can be public but settings or manually running a speedtest requires the password?
3. Can the style persist server side? If I change the style to stats - it’s only valid for the browser session.

Great work on this! Thanks

**Comment by gnmyt** [comment]
Hey! Sorry for the late response. First of all thanks for your feedback!

Your second suggestion has actually already been implemented. You just need to change the password level in the settings ( `Settings` » `Change password` » `Change level` )

![Screenshot_20230503_185335](https://user-images.githubusercontent.com/35641351/235985934-c49c895d-edad-4db5-8d38-904fe0633972.png)
![Screenshot_20230503_185416](https://user-images.githubusercontent.com/35641351/235986029-77acd0a3-b539-400c-ac9d-7eee4cdf5325.png)

I get the point that it's annoying when the settings change on different devices, but in the case of the language and view, it's better if the settings are saved client-side. 
Especially for instances that are public and people with different languages enter the site, it is better to let the users decide that for themselves which language they want and not force the server languange on them.

However, I will implement that MySpeed automatically uses the language of the browser and does not fall back to German all the time. :)

**Comment by jiriteach** [comment]
Awesome thanks! Using the browsers language works perfectly :) 
Will try and password level as well.

Cheers
