### ISSUE TITLE
Eher kleiner Fehler: Hinweise im Log bei der Installation

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#35]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

```
mv: das Verschieben von 'myspeed-development/cli' nach './cli' ist nicht möglich: Das Verzeichnis ist nicht leer
mv: das Verschieben von 'myspeed-development/docs' nach './docs' ist nicht möglich: Das Verzeichnis ist nicht leer
```

Dieser Fehler fiel mir beim Update der Dev-Version auf. Was genau eingeschränkt wird, kann ich nicht sagen. Es passiert in den Zeilen von dem Hinweis "`ℹ Info:  Download abgeschlossen. Entpacken läuft...`", nach dem Fehler erscheint diese Info: ```ℹ Info:  Die notwendigen Abhängigkeiten werden jetzt installiert...```
Die Funktion wird soweit nicht eingeschränkt. 

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Prinzipiell ist das nichts schlimmes, der Installer funktioniert auch mit diesen Warnungen. Ich verstehe allerdings, dass das ganze verwirrend sein kann. Die Warnungen werden in https://github.com/gnmyt/myspeed/commit/c6b7d090a0a761b4149927d39accd371536c8910 entfernt. Es sollte also nicht mehr passieren.

Vielen Dank fürs melden :)
