### ISSUE TITLE
Keine Reaktion beim Versuch, MySpeed ohne Wert zu pausieren

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#36]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Ich habe mal probiert, MySpeed ohne Wert zu pausieren. Leider mit Erfolg, in dem Fall wäre es wünschenswert eine Info zu bekommen, das ein Wert erforderlich ist. 

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Vielen Dank fürs melden. Gleich sollte es nicht mehr möglich sein, einen Dialog ohne Wert abzusenden
