### ISSUE TITLE
Development Version als OneClick Installer anbieten

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#4]
Wenn es die Dev Version gibt, warum auch nicht anbieten? Es gibt bestimmt freiwillige Tester, die diese Version vorab testen würden.

**Comment by gnmyt** [comment]
Ich habe nun einen Bereich für die [automatische Installation der Development-Version](https://github.com/gnmyt/myspeed/wiki/Einrichtung-Linux#automatische-installation) erstellt und das Skript so angepasst, dass die neuste Entwicklungsversion heruntergeladen wird. (Siehe  https://github.com/gnmyt/myspeed/commit/6fc0327e600cd97519fcb1898d3d03e4d773fd5a)
