### ISSUE TITLE
Log / Debug für Entwickler

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#41]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Bei unbekannten Fehlern wäre es von Vorteil, wenn man selbst Entwickler ist und den Fehler selbst beheben kann (wenn man möchte). Mein Gedanke wäre eine einfache Logfile. Alternativ wäre das melden des Problems als direkte Issue eine gute Möglichkeit, den Fehler direkt melden zu können.

**Comment by gnmyt** [comment]
Hey. Von welcher Art von Fehler reden wir hier? Fehler die auftreten, wenn ein Speedtest fehlschlägt oder wenn ein Fehler in der Konsole auftritt?

Die Fehler werden ja gespeichert und lassen sich auch sogar im Dashboard direkt ansehen wenn man auf das Icon dafür klickt

**Comment by pavl21** [comment]
Ich rede von einem Dump-Report, wo man sieht was genau vorgefallen ist. So können Entwickler auch Änderungen vorschlagen.

**Comment by gnmyt** [comment]
Entschuldige die verspätete Antwort. Ein kleiner Log für Fehler könnte ganz nützlich für den ein oder anderen sein. Ich füge das für das nächste Update mal hinzu :)
