### ISSUE TITLE
[Idee] Manuelle- und fehlgeschlagene Tests mit Zahlen versehen 

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#411]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

![image](https://github.com/gnmyt/myspeed/assets/36771750/ce560475-444c-45c7-a123-d7d0d99e295b)

Derzeit werden nur 2 farbige Kreise gezeigt, die so gut wie garnicht auf den ersten Blick wiedergeben, wie viele das sind oder ob es gut oder schlecht ist. Da hätte ich diese Idee (siehe Bild). Die Anzahl der jeweiligen Ereignisse werden mit einer großen Zahl gezeigt.

**Comment by gnmyt** [comment]
Das Konzept ist sehr gut. Ich werde mal schauen, ob sich das mit ChartJS umsetzen lässt. Danke! :)

**Comment by gnmyt** [comment]
Moin. Ist jetzt ein bisschen her und ich habe leider keine optimale Lösung gefunden, die Idee korrekt zu implementieren. Es gibt Workarounds, die sind aber nicht unbedingt ideal. Ich werde vermutlich in einem der nächsten Updates grundlegend die Charts nochmal überarbeiten. Trotzdem Danke! 

Falls du einen Weg findest, das zu implementieren, lass es mich gerne wissen.
