### ISSUE TITLE
Manueller Speedtest im Vordergrund stehen geblieben, im Hintergrund läufts weiter.

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#42]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Nach einem manuellen Test und einem Tabwechsel in Chrome scheint wohl ein kleiner Fehler aufgetreten zu sein. Nachdem ich zum MySpeed Tab zurück kam (ohne reload) war immernoch der laufende Speedtest.

![image](https://user-images.githubusercontent.com/36771750/185597145-084f1b71-a44e-45ee-b27e-a43a7a9c4b69.png)

obwohl der seit ner Stunde fertig ist. Nach einem Reload der Seite war alles wieder normal.

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Auch wenn ich glaube, dass Chrome bei längerer Nutzung einfach die Seite "pausiert" hat um Ressourcen zu sparen habe ich mal das Statussystem überarbeitet (#45). Außerdem denke ich, dass ein Speedtest normal keine Stunde dauert und man deswegen nicht unbedingt den Tab wechseln muss 😅
