### ISSUE TITLE
Möglichkeit, Daten länger als einen Tag zu speichern

### ISSUE THREAD

**Issue by bcsti** [gnmyt/MySpeed#46]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Um Ergebnisse, zum Beispiel als Beweis für den eigenen Internet-Provider zu sammeln, würde sich eine Historie als nützlich erweisen.

**Comment by gnmyt** [comment]
Hey. Dieses Feature wurde bereits in der neusten Entwicklungsversion (#33) hinzugefügt. Hierbei kann man selbst in den Einstellungen festlegen, welchen Zeitraum man sehen möchte. Mehr zur Umsetzung findest du auch in dieser PR.

Ich teste aktuell noch, ob es irgendwelche Bugs mit der Einführung dieser Funktion gibt, weshalb es noch keinen offiziellen Release dazu gibt. Falls du jedoch trotzdem diese Funktion testen möchtest, kannst du dir auch gerne mal [die Entwicklungsversion anschauen](https://myspeed.gnmyt.dev/setup/linux/) :)

**Comment by gnmyt** [comment]
Ich würde dieses Issue dann mal schließen. Falls du noch Fragen oder Anregungen hast, öffne gerne ein neues Issue
