### ISSUE TITLE
healthchecks.io Integration

### ISSUE THREAD

**Issue by bcsti** [gnmyt/MySpeed#47]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Benachrichtigung (auch Unterwegs), wenn das Internet Zuhause ausfällt.

**Comment by gnmyt** [comment]
Erstmal vielen Dank für die Idee. Ich selbst habe noch nie mit healthchecks.io gearbeitet, aber der Service hört sich vielversprechend an und könnte nützlich für das Projekt sein. Ich setze mich da später mal dran und integriere das Feature
