### ISSUE TITLE
Gotify integration not working

### ISSUE THREAD

**Issue by andreescocard** [gnmyt/MySpeed#480]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

Hi, i am using casaos and installed on It gotify and myspeed. Both on latest version, tested gotify with the token over curl and the notification was displayed as expected, however on myspeed with gotify server url and token It shows never executed.
I tried:
Running test manually and changed frequency to 1 minute without success.

Edit: telegram integration is not working too, shows never executed.
No log inside log folder

![Screenshot_20231130_001403_Brave](https://github.com/gnmyt/myspeed/assets/728365/e2b58fc7-f76a-4b44-b42b-77fdaab2fa97)

### What device are you using to access the page?

On mobile

### Which operating system is your MySpeed instance running on?

Linux

**Comment by gnmyt** [comment]
Hey, thanks for the report. Have you checked the `Send finished` or `Send error` boxes? You can find them directly under the token.

![Screenshot_20231130_144637](https://github.com/gnmyt/myspeed/assets/35641351/cf45a49f-d01e-4f89-8294-b1863a86e803)

**Comment by andreescocard** [comment]
Sorry i didn't see the checkboxes
Checked them and receive the messages correctly, thank you very much
