### ISSUE TITLE
[Feature] I want Chinese language

### ISSUE THREAD

**Issue by youlan2333** [gnmyt/MySpeed#487]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

I want Chinese language

**Comment by gnmyt** [comment]
Hey. I don't speak Chinese myself, so I used a translation service. If you don't mind looking through these translations [on Crowdin](https://crowdin.com/translate/myspeed/36/en-zhcn), I could add Chinese as a language.

If you find strings that have been translated incorrectly, feel free to submit the correct translation. If everything is ok, please let me know here :)

**Comment by youlan2333** [comment]
> Hey. I don't speak Chinese myself, so I used a translation service. If you don't mind looking through these translations [on Crowdin](https://crowdin.com/translate/myspeed/36/en-zhcn), I could add Chinese as a language.
> 
> If you find strings that have been translated incorrectly, feel free to submit the correct translation. If everything is ok, please let me know here :)

:)

**Comment by gnmyt** [comment]
Thanks! The language will be included in the next update (1.0.9)
