### ISSUE TITLE
Sonstige Dienste bei automatischen Tests deaktivieren

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#5]
Wenn z.B. Nextcloud oder andere Dienste auf demselben Computer/Server/Miniserver laufen, kann es das Testergebnis beeinträchtigen. Da wäre ein Wiki angebracht, das zeigt, wie man mit Crontab (oder etwas anderem) Dienste vorübergehend zu einem bestimmten Zeitpunkt, in der der Speedtest läuft (es ist ja immer dieselbe Stunde und Minute, meistens) , zu deaktivieren/pausieren/in den Wartungszustand zu versetzen.

**Comment by gnmyt** [comment]
In das System selbst integrieren, wie du mir das schon mal gesagt hast wird nicht funktionieren. Ich kann aber dem Nutzer die Möglichkeit geben, zu entscheiden, wann die Tests gemacht werden und den Crontab dann darauf anpassen.

**Comment by gnmyt** [comment]
Ich füge das dann die Tage ins Wiki hinzu und füge auch eine Funktion hinzu, um Tests um bestimmte Uhrzeiten zu machen :)

**Comment by gnmyt** [comment]
Update: [Der Eintrag im Wiki wurde erstellt](https://github.com/gnmyt/myspeed/wiki/FAQ#warum-sollte-ich-h%C3%A4ufigkeiten-konfigurieren). Ich habe das mit den bestimmten Uhrzeiten nun zu Häufigkeiten ersetzt. Das heißt, Tests lassen sich beispielsweise jede halbe Stunde, jede Stunde oder alle 3 Stunden ausführen. So kann man dies mit seinem eigenen Zeitplan vereinbaren und die Hintergrunddienste rechtzeitig ausschalten
