### ISSUE TITLE
Add NodeExporter Function to Scrape Metrics [Feature] 

### ISSUE THREAD

**Issue by fynnsh** [gnmyt/MySpeed#515]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Hi, fände es super sinnvoll einen Prometheus Endpunkt in der Anwendung zu integrieren sodass die Werte des letzten Tests abgerufen werden können.

**Comment by gnmyt** [comment]
Hey. Danke für das Einsenden dieser Idee. Ich habe noch nie selbst mit Prometheus gearbeitet, auf jeden Fall aber mal davon gehört. Ich informiere mich mal über eine Möglichkeit, wie sich das integrieren lässt.
Derzeit finde ich leider nicht allzu viel Zeit dafür. Ich halte dich allerdings hier auf dem laufenden, sobald es Updates dazu gibt.

**Comment by fynnsh** [comment]
Leider nur wenig erfahrung in Javascript aber so ungefähr sollte es gehen:

https://www.npmjs.com/package/prom-client

```javascript
const express = require('express');
const promBundle = require('express-prom-bundle');
const promClient = require('prom-client');

// Prometheus-Metriken registrieren
const register = new promClient.Registry();
promClient.collectDefaultMetrics({ register });

// Benutzerdefinierte Metriken erstellen
const counter = new promClient.Counter({
  name: 'meine_app_anzahl_anfragen',
  help: 'Anzahl der Anfragen an meine App',
  registers: [register],
});

const gauge = new promClient.Gauge({
  name: 'meine_app_aktive_benutzer',
  help: 'Anzahl der aktiven Benutzer in meiner App',
  registers: [register],
});

// ... Sie können weitere Metriken wie Histogramme oder Summaries hinzufügen

const app = express();
const metricsMiddleware = promBundle({includeMethod: true, includePath: true});

// Prometheus-Middleware einbinden
app.use(metricsMiddleware);

// Benutzerdefinierte Metriken aktualisieren
app.get('/', (req, res) => {
  counter.inc();  // Zählt jede Anfrage
  // ... Andere Logik für Ihre Route
  res.send('Hallo Welt!');
});

// Endpunkt für Prometheus Scraping
app.get('/metrics', async (req, res) => {
  res.set('Content-Type', register.contentType);
  res.end(await register.metrics());
});

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`Server läuft auf Port ${PORT}`);
});
```

**Comment by fynnsh** [comment]
Dann kann das ganze mit Prometheus und Grafana etwas detaillierter dargestellt werden.

![image](https://github.com/gnmyt/myspeed/assets/24509725/c42346be-8cc5-468e-907b-62f5cc5e1d53)


derzeit halt damit https://github.com/MiguelNdeCarvalho/speedtest-exporter realisiert wäre aber nice wenn deine Software es auch könnte..
