### ISSUE TITLE
Vereinfachung der Tage

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#52]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Wenn die Tests nicht länger als 1 min oder 7 Tage her ist, könnte man es so umändern:
Statt 30.08 -> vor 3 min.
Statt 27.08 -> vor 3 Tagen
Statt 30.08 -> vor 4 Std.

**Comment by gnmyt** [comment]
Hey. Ich verstehe hier den Ansatz hierbei allerdings würde ich trotzdem bei der aktuellen Version bleiben um das Design möglichst beständig und übersichtlich zu halten. Zudem würden manche angaben für mobile Geräte ein Problem darstellen
