### ISSUE TITLE
[Feature]  i want to add french

### ISSUE THREAD

**Issue by torik988** [gnmyt/MySpeed#524]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

I wanted to add french to the project.i'm french and i discovered your project.

**Comment by gnmyt** [comment]
Thank you! I've added French to [our Crowdin page](https://crowdin.com/project/myspeed). I don't speak French myself, so I can't really help with translating, but if you need any help with the Crowdin interface, feel free to ask.

Again, thanks for the effort :)
