### ISSUE TITLE
Crontab Info: Mehr Details bei dieser Einstellung

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MySpeed#53]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Es wäre hilfreich zu erfahren, was die derzeitige Einstellung bedeutet. Im Grund eine Übersetzung, so wie im Crontab.guru

![image](https://user-images.githubusercontent.com/36771750/187521882-87d21a9c-c826-44b6-aff1-370959579fe8.png)

**Comment by gnmyt** [comment]
Hey! Vielen Dank für die Idee. Als Hilfestellung wird nun wie auf dem Bild gezeigt angezeigt, wann der nächste Test laut der Cron-Expression ausgeführt wird.
Implementiert wird das in https://github.com/gnmyt/myspeed/pull/51/commits/ea7eb926f4eee240208ec3ead2b9b80a4a41a951

Beispiel:
![Screenshot](https://user-images.githubusercontent.com/35641351/187559778-76656888-bc4f-417c-b9c0-d66a77b640d8.png)
