### ISSUE TITLE
[Fehler] automatische vs manuelle Tests ergeben komplett andere Ergebnisse

### ISSUE THREAD

**Issue by mawe0815** [gnmyt/MySpeed#531]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Ich nutze MySpeed als Docker Container auf einem Synology NAS und habe folgendes Verhalten bemerkt:

Bei einem automatischen Test wird die Downloadgeschwindigkeit prinzipiell mit einer Geschwindigkeit zwischen 35 MBit/s bis 45 MBit/s gemessen. 
Bei einem manuell angestoßenen Test wird immer die realistische Geschwindigkeit von um die 800 MBit/s ermittelt.

Das Verhalten ist komplett unabhängig von äußeren Einflüssen und findet immer statt. 
Es hat den Anschein, als ob automatische Tests "gedrosselt" werden bzw. mit geringerer Priorität ausgeführt werden.

Der Docker Container läuft immer mit der selben Priorität. 

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

### Auf welchem Betriebssystem läuft deine MySpeed-Instanz?

Linux

**Comment by gnmyt** [comment]
Hm, ein solches Verhalten habe ich auch noch nicht bemerkt. Ich beobachte das ganze mal und versuche, das Problem zu reproduzieren. Vielen Dank schon mal fürs melden!
