### ISSUE TITLE
[Bug] Cannot specify port # for webhook

### ISSUE THREAD

**Issue by begunfx** [gnmyt/MySpeed#534]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

If I specify a port in the URL the webhook fails to send.

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by gnmyt** [comment]
Hi! Sorry for the late response. MySpeed should be able to send requests to webhooks with a port. (At least it worked fine during my tests)

However, it is important that the webhook you are sending this request to responds with a `200 OK` code. If not, MySpeed thinks the request didn't go through or has been declined.

If you want to test your webhooks, you can use a tool like [this](https://webhook.site/) or a self-hosted tool like [this one](https://github.com/tarampampam/webhook-tester).

**Comment by gnmyt** [comment]
I'm closing this issue for now. If you still think this might be a bug, feel free to re-open this issue anytime. :)
