### ISSUE TITLE
[Bug]  I am having trouble making a discord integration

### ISSUE THREAD

**Issue by lasuaa** [gnmyt/MySpeed#535]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

I installed speedtest on my raspberry pi4 using casaos and wanted to get notified for each speedtest on discord, but i cant get past the section that asks for webhook URL. the box just stays red and i cant save.. I dont really know if it is a bug or i am just bad, but would really appreciate some help :D!
![Skærmbillede 2024-01-25 210220](https://github.com/gnmyt/myspeed/assets/150937913/6de80f3f-b9e3-4377-8d7c-555ece6ce747)

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by WunderBliss** [comment]
@lasuaa Can you tell me how you resovled this? I am also facing the same problem on casaOS...

**Comment by panzer-arc** [comment]
> [@lasuaa](https://github.com/lasuaa) Can you tell me how you resovled this? I am also facing the same problem on casaOS...

It wouldn't let me save until I removed 'app' from the domain (matches example in the field). I don't think it's working still.
