### ISSUE TITLE
[Bug] Could not create the data folder. Please check the permission

### ISSUE THREAD

**Issue by b42n1** [gnmyt/MySpeed#540]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

When installing via Synology Container Manager, I get the following error:

```
myspeed-myspeed-1
date	stream	content
2024/01/28 03:07:04	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:06:03	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:05:10	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:42	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:26	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:19	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:14	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:10	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:08	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:06	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:04	stderr	Could not create the data folder. Please check the permission
2024/01/28 03:04:03	stderr	Could not create the data folder. Please check the permission
```

Tested with this:

```
name: myspeed
services:
    myspeed:
        ports:
            - 5216:5216
        volumes:
            - /volume1/docker/myspeed/data:/myspeed/data
        restart: unless-stopped
        container_name: myspeed
        image: germannewsmaker/myspeed
volumes:
    myspeed:
        external:
            name: myspeed
```

and this from mariushosting:
```
version: "3.9"
services:
  myspeed:
    container_name: MySpeed
    image: germannewsmaker/myspeed:latest
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 5216:5216
    volumes:
      - /volume1/docker/myspeed:/myspeed/data:rw
    environment:
      NODE_ENV: production
```

Couldn't find any env information to set a UID and GID.

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by catanbri** [comment]
I am having the exact same issue. the myspeed folder has read\write for the user everyone. I have even tried giving everyone full control over the folder and still experience the permission issue with the docker container.

**Comment by b42n1** [comment]
@catanbri your comment got me to read marius tutorial properly. I hadn't sawn that he adjusts the folder permissions. I found his tutorial after I had problems with the install.

Got it working after a few tries.

1. Remove everything. Also delete the docker folder. Changing the permissions afterwards didn't work for me.
2. Follow his guide. https://mariushosting.com/how-to-install-myspeed-on-your-synology-nas/

Working and running over 24 h now.
![image](https://github.com/gnmyt/myspeed/assets/20787965/04e9a4fd-932a-47d2-9f61-a08b325e97d5)
