### ISSUE TITLE
gotify Notification Priority

### ISSUE THREAD

**Issue by Hendrik292** [gnmyt/MySpeed#544]
### Allgemeines

- [x] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Gibt es eine Möglichkeit, wie man die Priorität der gotify Benachrichtigung einstellen kann? Normalerweise liegt sie nämlich jetzt immer bei 3 ich würde sie gerne aber höher haben.

**Comment by gnmyt** [comment]
Derzeit müsstest du das noch manuell in der Datei unter `server/integrations/gotify.js` anpassen. Ich erstelle aber mal eine PR, die es ermöglicht, in der Web-UI die Priorität zu ändern. Du hast dann das Update direkt in der Dev-Version oder in der nächsten Release-Version. Die dauert aber noch ein wenig
