### ISSUE TITLE
[Feature] Add `serverid` to `models/Speedtests`

### ISSUE THREAD

**Issue by scara** [gnmyt/MySpeed#545]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Hi,
I'm really new to _MySpeed_ and already loving it. Thanks for your efforts 💪!

I'm collecting data since two days and it would be helpful to look at the `serverid` for each run to manually compare the stats based on it.
The feature would be to add it to the model, store it and show it in the _Test Overview_ view w/o touching _Test statistics_.

TIA,
Matteo

**Comment by gnmyt** [comment]
Hey, nice to hear that you like the project. I like your idea and will implement it in the next update. Thanks for the suggestion!
