### ISSUE TITLE
[Feature] Pushover.net Notifications

### ISSUE THREAD

**Issue by ComputerComa** [gnmyt/MySpeed#573]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

First off I absolutely love your project. I would love to see [Pushover](https://pushover.net/api) as a option for notifications. They use a simple JSON API. Thanks!

**Comment by gnmyt** [comment]
Hey, happy to hear that you like the project. I'll take a look at the pushover.net api and implement the integration. Thanks for your suggestion!

**Comment by alephtaph** [comment]
Plus 1
