### ISSUE TITLE
Monitor Game Servers

### ISSUE THREAD

**Issue by tismofied** [gnmyt/MySpeed#589]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Is this even possible? I wonder if we could monitor game servers pings like Call of Duty or something similar?
I was already using speedtest tracker by Alexjustesen but when i saw this I like it a lot

**Comment by gnmyt** [comment]
Hi. Glad you like the project. I like the idea in general but I think that would be too much for MySpeed itself. MySpeed is primarily made for network speed tracking and I tried to make it as simple as possible to use.

If you want to track game servers, you might want to take a look at [Uptime Kuma](https://github.com/louislam/uptime-kuma). It's open source and supports a wide range of protocols to monitor the status of gameservers or other services.

**Comment by gnmyt** [comment]
I'm closing this issue for now. If you have another idea or general feedback, feel free to open another issue. :)
