### ISSUE TITLE
[Feature] Choose your own Database

### ISSUE THREAD

**Issue by 0xvisualiris** [gnmyt/MySpeed#594]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Hello,
I really love your GitHub project and use it all day hourly in my docker environment.
I'm using a Grafana instance also with Unifi Unpoller to collect all my data from my UniFi setup and got the idea to connect the MySpeed database also to Grafana. But there is a problem, that the SQLite database is not the best option to use it for Grafana. I would really love too use MySpeed with Grafana to have everything at one place where I can have a look for my network setup.

Maybe you can use a different database as the default so that MySpeed ​​users can use Grafana with a few clicks and use the time series graph.

**Comment by 0xvisualiris** [comment]
Ups, jetzt erst gesehen das ich auch auf Deutsche hätte schreiben können :D

**Comment by gnmyt** [comment]
Moin, ich bin einfach mal so frei und antworte auch direkt auf Deutsch. Erstmal freut es mich natürlich, dass dir das Projekt gefällt.

Mit Grafana habe ich persönlich noch nicht gearbeitet, aber eine Anbindung an unterschiedliche Datenbank-Softwares ist möglich. 

Würde in deinem Fall eine MySQL-Datenbank funktionieren? Dann würde ich mich die Tage mal daran setzen, eine Unterstützung für beide Typen, also `sqlite` und `mysql`, hinzuzufügen.

**Comment by 0xvisualiris** [comment]
Servus,
klar kein Problem. Erstmal danke für die schnelle Reaktion.

Ich kann folgende Fehlermeldung mitgeben von Grafana selbst:
"can not convert to wide series, expected long format series input but got not series"



Des weiteren kommt diese Information:
Time formatted columns
Columns with these names, will be formatted as time. This is required as SQLite has no native "time" format, but mostly strings and numbers. See: [SQLite3 Data Types Documentation](https://www.sqlite.org/datatype3.html)
For more information (like supported formats) see: [Plugin documentation](https://github.com/fr-ser/grafana-sqlite-datasource#support-for-time-formatted-columns)



Die Frag ist ob man das ganze allgemein umändern könnte. Aber das ganze ist nicht eilig :) Das ist eine private Grafana Umgebung und die baue ich gerade auf. Also nur kein Stress.

**Comment by gnmyt** [comment]
Moin, hat jetzt doch ein bisschen länger gedauert als erwartet. MySQL-Support ist jetzt in der neuen Entwicklungsversion implementiert. Bis zur nächsten Stable-Version wird es allerdings noch etwas dauern.
