### ISSUE TITLE
homepage integration

### ISSUE THREAD

**Issue by adresner** [gnmyt/MySpeed#614]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Can myspeed work with homepage? https://gethomepage.dev/latest/

**Comment by alephtaph** [comment]
Plus 1

**Comment by gnmyt** [comment]
Their [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines) state that the project needs to have at least 10 up-votes. I created a feature request [here](https://github.com/gethomepage/homepage/discussions/3514). 

If you're still interested, feel free to leave a up-vote there :)

**Comment by divemasterjm** [comment]
+1

**Comment by phil9309** [comment]
+1

**Comment by gnmyt** [comment]
I have opened a PR [on their GitHub page](https://github.com/gethomepage/homepage/pull/3662). This issue will be closed once it has been merged

**Comment by adresner** [comment]
This is great news!

**Comment by Kslim2912** [comment]
the widget is still not working in homepage.

**Comment by Kslim2912** [comment]
and there isn't a valid logo to use either.

**Comment by phil9309** [comment]
The widget is working fine.

![Screenshot_2024-08-10-20-32-30-62_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/2f66298e-8fe1-4a78-b101-012fca39cb7c)

You're right about the icon, I chose the icon from openspeedtest instead.

**Comment by gnmyt** [comment]
Currently, you need to define the icon using the url of the logo (https://gethomepage.dev/main/configs/services/#icons)

I've opened a PR on the repository which Homepage uses as icon sources (https://github.com/walkxcode/dashboard-icons/pull/741) but it may take some time for it to get merged.
