### ISSUE TITLE
[Bug] Completely different speed when performing auto / manual

### ISSUE THREAD

**Issue by bastienlg** [gnmyt/MySpeed#724]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

Hello, firstly thanks for the project, it's a great tool and as a developper too I love to see these things. I saw a strange behavior on my speedtest. When I trigger a manual speedtest, I have my normal bandwidth. But when an automatic one is called, my download is super low (the upload doesn't change that much)
Is the speedtest function the same for manual and auto ?
<img width="1414" alt="Capture d’écran 2024-06-25 à 13 32 09" src="https://github.com/gnmyt/myspeed/assets/114402159/6f3229a4-d40b-4229-8e80-1bb46967610b">

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by gnmyt** [comment]
Hey, glad you like the tool. I couldn't reproduce this issue myself so I have some steps you can try:

- Are there multiple instances of speedtests trackers in your network? To check, change your frequency (`Settings` > `Set frequency` > `Set manually`) to something more random (`8 * * * *` to schedule at minute 8)
- Does this also happen on other servers? Try going to `Settings` > `Change provider` and choose a different server from the list to check
- If that also doesn't help, try using a different provider. MySpeed also has support for LibreSpeed and Cloudflare. If it does not happen there, this might be related to the Speedtest CLI
- Speaking of the Speedtest CLI, if all the steps above didn't help, try running a speedtest using the [Speedtest CLI](https://www.speedtest.net/de/apps/cli) exactly at the start of an hour

Let me know if any of those steps helped or the issue still happens with the steps applied

**Comment by bastienlg** [comment]
It was the frequency ! I didn't even think about this, but it's logical. A lot of cron do health check speed test, and they use round hours to do so. And the upload didn't move because it doesn't overload a server that much and because users have way lower upload in general, so harder to saturate. I changed the frequency to 8 minutes past o'clock and it's good !
Have a nice day and thank you !

**Comment by bumgarb** [comment]
Manually setting the frequency worked for me as well.  Glad I found this!
