### ISSUE TITLE
Daten sichern

### ISSUE THREAD

**Issue by RobertoCravallo** [gnmyt/MySpeed#729]
### Allgemeines

- [X] Mein Feature existiert noch nicht in der neusten Version von MySpeed.
- [X] Ich habe überprüft, dass mein Feature noch von niemanden vorgeschlagen wurde.

### Deine Idee

Coole Idee und schöne Implementierung. Bin etwas überrascht, bzw. habe es eventuell nicht verstanden, aber wie kann ich die gemessenen Daten speichern? Ich möchte ja eventuell in 4 Wochen schauen, was heute so lief!!

**Comment by gnmyt** [comment]
Hi. MySpeed speichert grundsätzlich erstmal alle Tests für 30 Tage. Grund dafür sind die ersten Entwicklungen der App. Am Anfang konnten nur Tests bis zu 24 Stunden angezeigt werden, Statistiken gab es da ebenfalls noch nicht. Nur eine Listenansicht von allen Tests der letzten 24 Stunden. Das wurde dann mit Durchschnitten und Statistiken übersichtlicher gemacht und seitdem speichert MySpeed auch 30 Tage.

Möchtest du die Tests speichern und nach 30 Tagen noch sehen kannst du im Menü unter `Einstellungen` > `Speicher verwalten` > `Tests exportieren` die Tests in ein für dich präferiertes Format exportieren.

Zukünftig ist aber geplant, noch weiter in die Vergangenheit zu speichern und dann die einzelnen Monate/Jahre übersichtlich darzustellen. Ein genaues Datum kann ich dafür allerdings noch nicht nennen.

**Comment by RobertoCravallo** [comment]
Sorry!!! Mann bin ich blind!!! Danke für die Infos....

**Comment by gnmyt** [comment]
Alles gut, kein Problem. Ich schließe das Issue mal. Solltest du jedoch noch weitere Fragen dazu haben, öffne es einfach nochmal :)
