### ISSUE TITLE
Ping unter 1ms

### ISSUE THREAD

**Issue by DedBash** [gnmyt/MySpeed#8]
Hey, ich habe MySpeed heute Testweise auf meinen Server installiert und dabei ist mir Aufgefallen das wenn der Ping unter 1ms ist als x angezeigt wird
<img src="https://file.kiznaiver.systems/api/public/dl/Y8BeezAN?inline=true">
Die Letzten 4 Pings auf dem Bild sind vom Server `ID=37567` der 5. ist von einem anderen (habe die ID leider nicht mehr)

**Comment by pavl21** [comment]
Das passiert, wenn der Ping kleiner als 1 ist. Das wurde bereits in der Beta gefixt, kann aber noch etwas dauern bis es im neuen Release dabei ist.

**Comment by gnmyt** [comment]
Hey, danke für dein Issue!
Wie Paul schon gesagt hat passiert das ganze wenn der Ping kleiner als 1 (also 0) ist. Ich selbst habe ziemlich schlechtes Internet Zuhause und bin daher zu diesem Zeitpunkt nicht davon ausgegangen, dass man einen 0er Ping haben kann, weshalb die Software dann da von einem Fehler ausgeht. Das ganze wurde schon im Commit https://github.com/gnmyt/myspeed/commit/83f2cc1b4986a7dd1547ee05be3055389053eb83 behoben und wird im nächsten Release (1.0.2) auch nicht mehr erscheinen 👀
