### ISSUE TITLE
Could not open the database file. Maybe it is damaged?

### ISSUE THREAD

**Issue by Sawaya-ui** [gnmyt/MySpeed#9]
### Allgemeines

- [X] Ich habe auf die neuste Version von MySpeed aktualisiert.
- [X] Mein Bug wurde noch nicht gemeldet

### Der Fehler

Als ich den folgenden Command eingegeben habe kam der folgende Fehler:
`$env:NODE_ENV="production"; node server`

`Could not open the database file. Maybe it is damaged?`

### Auf welchem Gerät rufst du die Seite auf?

Im Browser

**Comment by gnmyt** [comment]
Hey. Hast du MySpeed auf einem Windows oder Linux-Gerät installiert?

**Comment by Sawaya-ui** [comment]
Windows

**Comment by gnmyt** [comment]
Okay. Navigiere bitte einmal in den Ordner, wo du MySpeed installiert hast (wenn du dich noch nicht darin befindest) und führe diesen Befehl mal aus: `node -e "db = require('better-sqlite3')('data/storage.db');"`

Sende diesen Fehler dann mal bitte hier rein (Daten wie Ordner kannst du zensieren)

**Comment by Sawaya-ui** [comment]
Error: \\?\C:\Users\**\Downloads\MySpeed-1.0.1\node_modules\better-sqlite3\build\Release\better_sqlite3.node is not a valid Win32 application.
\\?\C:\Users\**\Downloads\MySpeed-1.0.1\node_modules\better-sqlite3\build\Release\better_sqlite3.node
←[90m    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at bindings (C:\Users\**\Downloads\MySpeed-1.0.1\node_modules\←[4mbindings←[24m\bindings.js:112:48)
    at new Database (C:\Users\**\Downloads\MySpeed-1.0.1\node_modules\←[4mbetter-sqlite3←[24m\lib\database.js:48:64)
    at Database (C:\Users\**\Downloads\MySpeed-1.0.1\node_modules\←[4mbetter-sqlite3←[24m\lib\database.js:11:10)
    at [eval]:1:31
←[90m    at Script.runInThisContext (node:vm:129:12)←[39m {
  code: ←[32m'ERR_DLOPEN_FAILED'←[39m
}

**Comment by gnmyt** [comment]
Das liegt dann wohl an dem vorgefertigten Build der Module. Das kann bei einer anderen Architektur oder auch anderen Node-Version auftreten.

Der einfachste Weg, das zu beheben wäre das löschen des `node_modules` Ordners und das erneute kompilieren der Module mit `npm install`

Versuch das bitte mal und starte dann MySpeed erneut
